build: version numpy dists and relocate pycrossenv

diff --git a/python3-opencv/BUILD b/python3-opencv/BUILD
--- a/python3-opencv/BUILD
+++ b/python3-opencv/BUILD
@@ -17,9 +17,9 @@ pkg_version="4.11.0"
 pkg_name="python3-opencv"
 # [OPTIONAL, seperated by commas, NO-SPACE]. e.g., pkgname1>=0.5,pkgname2==1.0.0,pkgname2<2.0.0,pkgname3
 # NOTE: python3>=3.9 use numpy>=2. See https://github.com/opencv/opencv-python/blob/4.x/pyproject.toml
-pkg_deps="python3>=3.9,python3-numpy2>=2,openblas,ffmpeg>=4,python3-wheel,python3-setuptools"
+pkg_deps="python3>=3.9,python3-numpy>=2,openblas,ffmpeg>=4,python3-wheel,python3-setuptools"
 # [OPTIONAL, seperated by commas, NO-SPACE]
-pkg_build_deps="python3>=3.9,python3-numpy2>=2,openblas,ffmpeg>=4,python3-wheel,python3-setuptools"
+pkg_build_deps="python3>=3.9,python3-numpy>=2,openblas,ffmpeg>=4,python3-wheel,python3-setuptools"
 ########### At Least ONE is REQUIRED ##############
 # [OPTIONAL, VALID-URL]
 pkg_source_url="https://github.com/opencv/opencv-python.git"
@@ -101,12 +101,13 @@ native_env_hook() {
 # 	if you set _custom_download_source_continue="false" caz default build process will use
 custom_download_source() {
 	
-	mkdir -p ${current_source_root}
-	git clone $pkg_source_url ${current_source_root}
-	pushd ${current_source_root}
-	git switch 4.x
-	git submodule sync && git submodule update --init --recursive
-	popd
+	rm -rf "${current_source_root}"
+	git clone "$pkg_source_url" "${current_source_root}" || return 1
+	pushd "${current_source_root}" || return 1
+	git switch 4.x || { popd; return 1; }
+	git submodule sync || { popd; return 1; }
+	git submodule update --init --recursive || { popd; return 1; }
+	popd || return 1
 
 	_custom_download_source_continue=false
 }
@@ -135,13 +136,13 @@ prebuilt_patch_once_hook() {
 #  - postbuilt_hook will still be called after custom_build set _custom_build_continue="false"
 custom_build() {
 	# make opencv's cmake happy
-	mkdir -p ${target_root_prefix_without_pkgname}/include
+	mkdir -p "${target_root_prefix_without_pkgname}/include" || return 1
 	
-	setup_pycrossenv
+	setup_pycrossenv || return 1
 
-	pushd ${current_source_root}
+	pushd "${current_source_root}" || { destroy_pycrossenv || true; return 1; }
 	# use $CFLAGS in env when building a python pkg
-	build_cmakeproj_with_deps "opencv" "$(get_pkg_names_from_deps $pkg_build_deps)" "\
+	build_cmakeproj_with_deps "opencv" "$(get_pkg_names_from_deps "$pkg_build_deps")" "\
 		-DCMAKE_FIND_ROOT_PATH=${HOST_PYTHON_DIST} \
 		-DPYTHON_INCLUDE_DIRS=${HOST_PYTHON_DIST}/include \
 		-DPYTHON3_INCLUDE_PATH=${HOST_PYTHON_DIST}/include/python${PY_VERSION} \
@@ -151,34 +152,50 @@ custom_build() {
 		"$CFLAGS" \
 		"-D__MUSL__ -D__OPENHARMONY__ -D__OHOS__" \
 		"$LDFLAGS" \
-		"20"
+		"20" \
+	|| { error "build_cmakeproj_with_deps failed"; popd; destroy_pycrossenv || true; return 1; }
 
 	popd
 
-	destroy_pycrossenv
+	destroy_pycrossenv || return 1
 
 	_custom_build_continue=false
 }
 
 # Hook: called after leaving build dir (staging area ${target_root_with_pkgname} is generated)
 postbuilt_hook() {
+	local _cv2_pkg_dir
+	local _cv2_so
+
+	_cv2_pkg_dir="$(get_pkg_dst_dir opencv)/${OHOS_LIBDIR}/python${PY_VERSION}/site-packages/cv2"
+	_cv2_so="${_cv2_pkg_dir}/python-${PY_VERSION}/cv2.cpython-${PY_VERSION_CODE}-${OHOS_CPU}-linux-ohos.so"
+
+	if [ ! -d "${_cv2_pkg_dir}" ]; then
+		error "missing cv2 package directory: ${_cv2_pkg_dir}"
+		return 1
+	fi
+	if [ ! -f "${_cv2_so}" ]; then
+		error "missing cv2 extension: ${_cv2_so}"
+		return 1
+	fi
+
 	# patch dylib
-	patchelf --add-needed libpython${PY_VERSION}.so $(get_pkg_dst_dir opencv)/${OHOS_LIBDIR}/python${PY_VERSION}/site-packages/cv2/python-${PY_VERSION}/cv2.cpython-${PY_VERSION_CODE}-${OHOS_CPU}-linux-ohos.so
+	patchelf --add-needed "libpython${PY_VERSION}.so" "${_cv2_so}" || return 1
 	
 	local _pkgd=opencv_python-4.11.0.86
 	local _pkgw=${_pkgd}.dist-info
 	local _zipn=${_pkgd}-cp${PY_VERSION_CODE}-cp${PY_VERSION_CODE}-linux_${OHOS_CPU}
 
 	local out=${target_root_with_pkgname}/${OHOS_LIBDIR}/python${PY_VERSION}/site-packages/
-	mkdir -p ${out}
-	pushd ${out}
-	cp -r $(get_pkg_dst_dir opencv)/${OHOS_LIBDIR}/python${PY_VERSION}/site-packages/cv2 .
-	cp -r ${native_project_root}/${_pkgw} .
-	${native_project_root}/RECORD.GEN.sh cv2 ${_pkgw} > RECORD
-	mv RECORD ${_pkgw}
-	zip -r ${_zipn}.zip ${_pkgw} cv2
-	mv ${_zipn}.zip ${PYPKG_OUTPUT_WHEEL_DIR}/${_zipn}.whl
-	popd
+	mkdir -p "${out}" || return 1
+	pushd "${out}" || return 1
+	cp -r "${_cv2_pkg_dir}" . || { popd; return 1; }
+	cp -r "${native_project_root}/${_pkgw}" . || { popd; return 1; }
+	"${native_project_root}/RECORD.GEN.sh" cv2 "${_pkgw}" > RECORD || { popd; return 1; }
+	mv RECORD "${_pkgw}" || { popd; return 1; }
+	zip -r "${_zipn}.zip" "${_pkgw}" cv2 || { popd; return 1; }
+	mv "${_zipn}.zip" "${PYPKG_OUTPUT_WHEEL_DIR}/${_zipn}.whl" || { popd; return 1; }
+	popd || return 1
 }
 
 ################ self-defined functions (local) goes below ################
