feat. add openjdk, cairo(no glib support), pixman, cups; fix. mesa, xorg broken deps

diff --git a/openjdk/BUILD b/openjdk/BUILD
--- a/openjdk/BUILD
+++ b/openjdk/BUILD
@@ -12,16 +12,17 @@ setup() {
 # TODO: please fill in the variables for this package
 
 # [REQUIRED, NON-EMPTY, SEMVER]
-pkg_version="25.2.2"
+pkg_version="21.0.10"
 # [REQUIRED, NON-EMPTY, NO-SPACE]
-pkg_name="mesa"
+pkg_name="openjdk"
 # [OPTIONAL, seperated by commas, NO-SPACE]. e.g., pkgname1>=0.5,pkgname2==1.0.0,pkgname2<2.0.0,pkgname3
-pkg_deps="xorg>=7.0,libdrm>2.0,glslang>=16.0,llvm>20.0,SPIRV-LLVM-Translator>=21.0,zstd>=1.0"
+pkg_deps="fontconfig>=2,freetype>2.0,cups>=2,xorg,alsa-lib,libffi>=3"
 # [OPTIONAL, seperated by commas, NO-SPACE]
-pkg_build_deps="xorg>=7.0,libdrm>2.0,glslang>=16.0,llvm>20.0,SPIRV-LLVM-Translator>=21.0,SPIRV-Headers>=1.4,SPIRV-Tools>=1.4,zstd>=1.0,fontconfig>=2.17,freetype>2.0,libncursesw>6.0,libreadline>8.0,icu>70.0,libexpat>2.0,libxml2>2.0,libiconv>1.0,python3,python3-build,python3-setuptools"
+# NOTE: you need to add build deps "python3,python3-build,python3-setuptools" if you use setup_pycrossenv in hooks
+pkg_build_deps="fontconfig>=2,freetype>2.0,cups>=2,xorg,alsa-lib,libffi>=3"
 ########### At Least ONE is REQUIRED ##############
 # [OPTIONAL, VALID-URL]
-pkg_source_url="https://mesa.freedesktop.org/archive/mesa-25.2.2.tar.xz"
+pkg_source_url="https://github.com/openjdk/jdk21u/archive/refs/tags/jdk-21.0.10+6.zip"
 # [OPTIONAL, VALID-URL]
 pkg_release_url=""
 ###################################################
@@ -33,16 +34,29 @@ pkg_support_archs="x86_64,aarch64,arm"
 # NOTE:
 #  - "pure-python" is ONLY valid for those packages without ANY native package dependency.
 #  - "custom" will skip the default build process
-pkg_build_type="meson"
+#  - add "python3,python3-build,python3-wheel,python3-setuptools" to pkg_build_deps if you use "pure-python"
+#  - you are responsible to set setup_pycrossenv if you set pkg_build_type == "meson", ensure meson, and use destroy_pycrossenv before finishing building this package.
+pkg_build_type="custom"
 # [OPTIONAL]
-pkg_build_parallism="20"
+pkg_build_parallism=""
+# [OPTIONAL: empty or Y]
+pkg_force_clean_build=""
 
 ####### build type related (all OPTIONAL) #######
 
-pkg_build_autotools_extra_configure_flags=""
+pkg_build_autotools_extra_configure_flags="\
+--with-jvm-variants=server \
+--with-boot-jdk=/home/gjy/Desktop/tmp-robot/tools_ohloha/ohloha_pkgs/jdk-21.0.2 \
+--host=${OHOS_CPU}-unknown-linux-musl \
+--target=${OHOS_CPU}-unknown-linux-musl \
+--with-toolchain-type=clang \
+--with-sysroot=${HOST_SYSROOT} \
+--with-extra-cflags=\"${CFLAGS}\" \
+--with-extra-cxxflags=\"${CXXFLAGS}\" \
+--with-extra-ldflags=\"${LDFLAGS}\""
 # fill in a relative path to the ${current_source_root} (defined below)
 pkg_build_autotools_bootstrap_script=""
-pkg_build_autotools_suffix_configure_flags=""
+pkg_build_autotools_suffix_configure_flags="AR=${AR} AS=${AS} STRIP=${STRIP} NM=${NM} OBJCOPY=${OBJCOPY} OBJDUMP=${OBJDUMP} CXXFILT=${OHOS_SDK}/native/llvm/bin/llvm-cxxfilt BUILD_CC=${OHOS_SDK}/native/llvm/bin/clang BUILD_CXX=${OHOS_SDK}/native/llvm/bin/clang++ BUILD_LD=${LD} BUILD_AR=${AR} BUILD_AS=${AS} BUILD_STRIP=${STRIP} BUILD_NM=${NM} BUILD_OBJCOPY=${OBJCOPY}"
 pkg_build_autotools_configure_dir=""
 pkg_build_autotools_make_install_target=""
 
@@ -55,8 +69,8 @@ pkg_build_cmake_extra_ldflags=""
 pkg_build_cmake_extra_cmake_findroot_path=""
 
 # fill in a absolute path
-pkg_build_meson_cross_file="${MESON_CROSS_FILE_BASE}"
-pkg_build_meson_extra_meson_flags="-Dcpp_rtti=false -Dvalgrind=disabled -Dplatforms=x11 -Dgallium-drivers=llvmpipe -Dvulkan-drivers=swrast"
+pkg_build_meson_cross_file=""
+pkg_build_meson_extra_meson_flags=""
 pkg_build_meson_extra_cflags=""
 pkg_build_meson_extra_ldflags=""
 pkg_build_meson_extra_cmake_prefix_path=""
@@ -93,7 +107,7 @@ pkg_build_meson_extra_cmake_findroot_path=""
 # Hook: called before setup.sh is sourced
 # NOTE:
 #  - failure in this function will terminate this script immediately
-#  - you can NOT use local variables defined above. you can only use ${native_project_root}, ${native_sources_root} built by builder.sh
+#  - you can NOT use local variables defined above. you can only use ${native_project_root}, ${native_sources_root}, ${native_dst_root} built by builder.sh
 native_env_hook() {
 	:
 }
@@ -114,31 +128,16 @@ fi
 
 # Hook: called before entering build dir
 prebuilt_patch_hook() {
-
-	setup_pycrossenv
-	# destroy in post-built hook
-
-	reset_meson $MESON_CROSS_FILE_BASE
-	# preparing build-time python deps before building mesa
-	BUILDTIME_PY=$(which build-python)
-	sed -i "s|^\(python[[:space:]]*=[[:space:]]*\).*|\1'${BUILDTIME_PY}'|" $MESON_CROSS_FILE_BASE
-	# using build-time (not runtime) python on the host machine
-	build-pip install packaging mako pyyaml meson
-
-	# patch meson for ohos
-	sed -i -e "\|ohos|! s|^\(system_has_kms_drm[[:space:]]*=[[:space:]]*.*'linux',[[:space:]]*\)\('sunos',.*\)$|\1'ohos', \2|" \
-		-e "\|ohos|! s|^\(if with_platform_android and get_option('platform-sdk-version').*\)$|\1 or 'ohos' == 'ohos'|" \
-		${current_source_root}/meson.build
-	# patch for not supporting pthread_cancel
-	sed -i -e "\|//|! s|\(pthread_cancel(.*);\)|// \1\nprintf(\"OHOS not support pthread_cancel\");exit(1);|g" \
-		-e "\|//|! s|\(pthread_setcanceltype(.*);\)|// \1\nprintf(\"OHOS not support pthread_setcanceltype\");exit(1);|g" \
-		${current_source_root}/src/vulkan/wsi/wsi_common_display.c
+	:
 }
 
 # Hook: same as `prebuilt_patch_hook` but executed once if the source directory is not changed (mark file PATCHED)
 # NOTE: it will be executed BEFORE prebuilt_patch_hook
 prebuilt_patch_once_hook() {
-	:
+	pushd ${current_source_root}
+	patch -p0 --dry-run < ${PATCH_FILE_ROOT}/oh-openjdk21.0.10+35.patch
+	patch -p0 < ${PATCH_FILE_ROOT}/oh-openjdk21.0.10+35.patch
+	popd
 }
 
 # Hook: customize building process.
@@ -147,21 +146,62 @@ prebuilt_patch_once_hook() {
 #  - You can set cross-compiling related global variables here (like CFLAGS)
 #  - postbuilt_hook will still be called after custom_build set _custom_build_continue="false"
 custom_build() {
-	
-	# add special headers
-	CFLAGS="-I$(get_pkg_dst_dir freetype)/include/freetype2 -I$(get_pkg_dst_dir libncursesw)/include/ncursesw -I$(get_pkg_dst_dir libreadline)/include/readline -D_GNU_SOURCE $CFLAGS"
-	CXXFLAGS=$CFLAGS
-	CPPFLAGS="-D_GNU_SOURCE $CPPFLAGS"
-	# fix llvm-config failure
-	LDFLAGS="-lLLVM-21 $LDFLAGS"
-	PKG_CONFIG_LIBDIR="$PKG_CONFIG_LIBDIR:$(get_pkg_dst_dir xorg)/share/pkgconfig"
 
-	_custom_build_continue=true
+	pushd ${current_source_root}
+	
+	chmod u+x configure
+	
+	local _deps=$(get_pkg_names_from_deps "$pkg_build_deps")
+	local _dep
+	for dep in $_deps; do
+		CFLAGS="${CFLAGS} -I$(get_pkg_dst_dir $dep)/include"
+		LDFLAGS="$LDFLAGS -L$(get_pkg_dst_dir $dep)/${OHOS_LIBDIR}"
+		PKG_CONFIG_LIBDIR="$PKG_CONFIG_LIBDIR:$(get_pkg_dst_dir $dep)/${OHOS_LIBDIR}/pkgconfig"
+	done
+	# c++ supports
+	CXXFLAGS="${CFLAGS} ${CXXFLAGS} -I${OHOS_SDK}/native/llvm/include/libcxx-ohos/include/c++/v1"
+	LDFLAGS="${LDFLAGS} -lc++_shared"
+	# freetype use special header dir
+	./configure \
+		--prefix=${target_root_prefix_without_pkgname} \
+		--with-jvm-variants=server \
+		--with-boot-jdk=/usr \
+		--openjdk-target=${OHOS_CPU}-unknown-linux-musl \
+		--with-toolchain-type=clang \
+		--with-sysroot=${HOST_SYSROOT} \
+		--with-extra-cflags="${CFLAGS} -DMUSL_LIBC -DLIBC=musl -Wno-sign-compare" \
+		--with-extra-cxxflags="${CXXFLAGS} -DMUSL_LIBC -DLIBC=musl -Wno-sign-compare" \
+		--with-extra-ldflags="${LDFLAGS}" \
+		--with-freetype-include=$(get_pkg_dst_dir freetype)/include/freetype2 \
+		--with-freetype-lib=$(get_pkg_dst_dir freetype)/${OHOS_LIBDIR} \
+		CC="${OHOS_SDK}/native/llvm/bin/${OHOS_CPU}-unknown-linux-ohos-clang" \
+		CXX="${OHOS_SDK}/native/llvm/bin/${OHOS_CPU}-unknown-linux-ohos-clang++" \
+		AR=${AR} AS=${AS} STRIP=${STRIP} NM=${NM} OBJCOPY=${OBJCOPY} OBJDUMP=${OBJDUMP} \
+		CXXFILT=${OHOS_SDK}/native/llvm/bin/llvm-cxxfilt \
+		BUILD_CC="/usr/bin/clang -isystem /usr/lib/llvm-12/include/c++/v1 -isystem /usr/lib/llvm-12/include -isystem /usr/include" \
+		BUILD_CXX="/usr/bin/clang++ -stdlib=libc++ -nostdinc++ -Wno-unused-command-line-argument -isystem /usr/lib/llvm-12/include/c++/v1 -isystem /usr/lib/llvm-12/include -isystem /usr/include" \
+		BUILD_LD=/usr/bin/lld BUILD_AR=/usr/bin/llvm-ar BUILD_AS=/usr/bin/llvm-as BUILD_STRIP=/usr/bin/llvm-strip BUILD_NM=/usr/bin/llvm-nm BUILD_OBJCOPY=/usr/bin/llvm-objcopy || { error "openjdk configure error"; popd; return 1; }
+		#--with-boot-jdk=/home/gjy/Desktop/tmp-robot/tools_ohloha/ohloha_pkgs/jdk-21.0.2 \
+	unset CFLAGS CXXFLAGS LDFLAGS
+	make images || { error "openjdk xcompile error"; popd; return 1; }
+	# install manually
+	# make install || { error "openjdk install error"; popd; return 1; }
+	
+	popd
+
+	if [ -d ${target_root_with_pkgname} ]; then
+		rm -rf ${target_root_with_pkgname}
+	fi
+	# install to local
+	mkdir -p ${target_root_with_pkgname}/local
+	cp -r ${current_source_root}/build/linux-${OHOS_CPU}-server-release/images/jdk/* ${target_root_with_pkgname}/local/
+
+	_custom_build_continue=false
 }
 
 # Hook: called after leaving build dir (staging area ${target_root_with_pkgname} is generated)
 postbuilt_hook() {
-	destroy_pycrossenv || true
+	:
 }
 
 ################ self-defined functions (local) goes below ################
